spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092          # 指定kafka server的地址，集群配多个，中间，逗号隔开
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      group-id: default_consumer_group        #群组id
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
  #============================rabbitmq配置======================================
  rabbitmq:
    host: 127.0.0.1      # rabbitmq 的连接地址
    port: 5672
    virtual-host: /sweb    # rabbitmq 的虚拟host
    username: sweb
    password: sweb
    publisher-confirms: true   #如果对异步消息需要回调必须设置为true
    listener:
      simple:
        # 初始化并发消费者数量
        concurrency: 10
        # 并发消费者最大值
        max-concurrency: 20
        # 每个消费这从队列可拉取的数量
        prefetch: 5
